name: ciflow_linux

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  pull_request:
    types: [unassigned]
  push:
    branches:
      - master
      - main

jobs:
  label_guard:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || contains(github.event.label.name, 'ciflow/default')
    steps:
      - run: echo "noop"
  linux_1:
    needs: [label_guard]
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60s
  linux_circleci_1:
    needs: [label_guard]
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60s
  linux_circleci_2:
    needs: [label_guard]
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60s
