name: ciflow_windows_cuda

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  pull_request:
    types: [unassigned]
  push:
    branches:
      - master
      - main

jobs:
  label_guard:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ciflow/cuda')
    steps:
      - run: echo "noop"
  windows_job1:
    needs: [label_guard]
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30s
